### ISSUE TITLE
Does not install with Workflow 5.x

### ISSUE THREAD

**Issue by klimenttoshkov** [zerodahero/laravel-workflow#10]
In order to install the package you need to stick with Workflow 4.x while there is 5.x release. have you considered updating?

**Comment by zerodahero** [comment]
Since creating this fork, the upstream branch (brexis) has resumed activity, so I'm considering packaging up some of the non-update changes and opening a PR on that package instead of maintaining the two separately.

Are there features only in this fork that you're using?

**Comment by klimenttoshkov** [comment]
It doesn't seem active to me, the only recent merged PR was simple change in Str/Arr helpers (which you should do as well).

It is also not updated to accept Workflow 5.x.

Featurewise - no, I think I use the basic functionalities but I like the possibility to dynamically load workflow definition in service provider.

**Comment by klimenttoshkov** [comment]
But in general I also prefer to have one package, updated and good to go.

**Comment by zerodahero** [comment]
Ok, I took a look at upgrading to Workflow 5.x. Seems like a minor-enough change for this package, the main hold up is that Laravel 6 is still version-locked to the Symfony 4 components. It's possible to bump the workflow component only, but I'd rather not mix symfony versions.

It looks like Laravel v7 is going to be released the first week in March, so I'll wait for that to push a release to this package.

In the meantime, I'm creating a 3.x branch which will track the changes off the Laravel dev-7x branch. Feel free to use it and submit any issues on it, but I won't officially release it until after Laravel 7 is released.

**Comment by zerodahero** [comment]
If you're switching over to that branch, the main breaking change (besides dependencies) is that the config no longer accepts "arguments" it accepts a "property" to fit more in line with the v5 interface for MethodMarkingStore.

**Comment by klimenttoshkov** [comment]
Makes sense to me, I will wait for L7

**Comment by klimenttoshkov** [comment]
7 was just released

**Comment by zerodahero** [comment]
Just released! https://github.com/zerodahero/laravel-workflow/releases/tag/v3.0.0
Let me know if you encounter anything unexpected, the changes to this packaged ended up being fairly minimal.

**Comment by riddla** [comment]
@zerodahero, as I'm helping with the Laravel 7 version of https://github.com/brexis/laravel-workflow/pull/73 – can you speak to the differences between the original version and your fork?

Maybe there is a way "back"? ;)

**Comment by zerodahero** [comment]
@riddla Yes, definitely! I forked this because (1) we needed an up to date and maintained package, which the brexis one wasn't at the time, and (2) we wanted to load workflow definitions from a configurable store (DB in our case). There are a couple methods added into the registry that keep a record of the workflows loaded (to prevent double loading), but otherwise not much changed.

Specifically, the bump to support Laravel 7 was just addressing using MethodMarkingStore as the only store. I am yet to implement a "hands free" version, so right now the methods (getMarking, setMarking) have to be added in manually.

**Comment by klimenttoshkov** [comment]
Could you please provide an example how to load workflow from db? I am afraid I could not understand it so far.
—
Kliment Toshkov
mail@klimenttoshkov.com

**Comment by riddla** [comment]
@zerodahero, how do you implement the `getMarking` and `setMarking` methods? Can you give an example? I'm hitting this error also in https://github.com/brexis/laravel-workflow/pull/73 ...

**Comment by zerodahero** [comment]
@riddla It's on my list to come up with a more magical way of doing this (read: developer friendly), but haven't implemented one yet. Right now (and this is poorly documented), you'll need to add the getMarking and setMarking methods on your own (or getState, setState, etc). A few ways I was thinking about implementing it in a simpler way:

1.) Override the method store to use the Laravel accessors, then implement those in the WorkflowTrait on the models.
2.) Force the marking to always be "marking" and use the WorkflowTrait to create accessors linked to the `getMarking` and `setMarking` methods.
3.) Keep it as is, and get people used to interacting more closely with the symfony component itself. This approach would be nice since it could ease the implementation help requests, but isn't ideal from a plug n' play approach.

**Comment by zerodahero** [comment]
@klimenttoshkov Take a look at the readme for "tracking mode": https://github.com/zerodahero/laravel-workflow#use-in-tracking-mode, that should have everything you need to load a workflow from a DB.
