### ISSUE TITLE
How subscribe to event

### ISSUE THREAD

**Issue by devascolades** [zerodahero/laravel-workflow#11]
Hello,

I know event and listener with laravel, but I don't understand how use BlogPostWorkflowSubscriber.
How to subscribe to call onleave function for example.
Could someone give a full example, please ?

Fabien

**Comment by zerodahero** [comment]
All of the workflow events work like the Laravel events, so following the documentation on this page: https://laravel.com/docs/6.x/events#event-subscribers should be all you need to get going.

The only thing that's "special" about this package is that it allows the Symfony style of event listening. So, rather than needing to listen to the event class itself, you can use the wildcards (*). Take a look at the readme here: https://github.com/zerodahero/laravel-workflow#use-the-events and let me if anything is unclear and we can work to improve the docs.
