### ISSUE TITLE
laravel 6 issue

### ISSUE THREAD

**Issue by Azmeer-crescent** [zerodahero/laravel-workflow#19]
composer require zerodahero/laravel-workflow:2.1.0
gives me this for Laravel 6

Package manifest generated successfully.
> @php artisan ide-helper:generate

   Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to ZeroDaHero\LaravelWorkflow\WorkflowRegistry::__construct() must be of the type array, null given, called in \laravel_test\vendor\zerodahero\laravel-workflow\src\WorkflowServiceProvider.php on line 48

  at \laravel_test\vendor\zerodahero\laravel-workflow\src\WorkflowRegistry.php:59
    55|      * @param  array $config
    56|      * @param  array $registryConfig
    57|      * @throws \ReflectionException
    58|      */
  > 59|     public function __construct(array $config, array $registryConfig = null)
    60|     {
    61|         $this->registry = new Registry();
    62|         $this->config = $config;
    63|         $this->registryConfig = $registryConfig ?? $this->getDefaultRegistryConfig();

  Exception trace:

  1   ZeroDaHero\LaravelWorkflow\WorkflowRegistry::__construct([])
      \laravel_test\vendor\zerodahero\laravel-workflow\src\WorkflowServiceProvider.php:48

  2   ZeroDaHero\LaravelWorkflow\WorkflowServiceProvider::ZeroDaHero\LaravelWorkflow\{closure}(Object(Illuminate\Foundation\Application), [])
      \laravel_test\vendor\laravel\framework\src\Illuminate\Container\Container.php:799

  Please use the argument -v to see more details.
Script @php artisan ide-helper:generate handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by zerodahero** [comment]
Just tried it out on a fresh install of Laravel 6, everything works as expected.

Looks like you've got another package that's trying to do something without passing in the proper config. The line `@php artisan ide-helper:generate` is not a default Laravel script.

You can try the composer require with `--no-scripts` and see if that works. Closing this for now, since it doesn't seem to be related to the package itself. Feel free to reopen if I'm wrong.
