### ISSUE TITLE
Applying a workflow that features a place in multiple transitions - all guards related to place execute

### ISSUE THREAD

**Issue by erikacamilleri** [zerodahero/laravel-workflow#25]
I am wondering whether this behaviour is intentional. I have been debugging an issue in my project and I noticed that when applying a workflow like so:

`$this->workflow_apply('prepare', 'order_shipping_states_graph');`

Whereby the workflow has defined:

```
'prepare' => [
'from' => [ 'ready', 'being_prepared'] 
'to' => ['being_prepared']
],
'pick' => [
from => ['being_prepared']
 to => ['ready_to_ship']
]
```

Then both `guardPrepare` and `guardPick` are being executed in the respective workflow subscriber.

I would expect that since there is the transition specified, then only that guard would execute.

**Comment by zerodahero** [comment]
Yeah, I've run into similar issues. Unfortunately guards are run for every possible transition as part of the first check to see if the transition is valid. That's actually part of the Symfony component, so not much control over that here. I'll double check the Symfony 5 changes, since that was an older issue for me.

I'm curious, in this instance though, if having the same place in the `from` and `to` of the `prepare` transition is affecting that? Is it the same issue without `being_prepared` in the `from`?

**Comment by zerodahero** [comment]
A bit more detail on that, in case you (or others) are interested. Here's the rough flow of what happens when you apply a transition:

1. `workflow_apply` grabs the instance of the workflow registry, fetches the relevant workflow (object) and proxies the call to the Symfony Workflow component (that's all through this package's facade: `WorkflowFacade` and `WorkflowRegistry`)
2. In `Symfony\Component\Workflow\Workflow@apply` we get the marking, then for each transition _in the workflow definition_ run the guards (`buildTransitionBlockerListForTransition`) to compile a list of "approvedTransitions".
3. If the provided transition exists and is approved, we do the transition (leave, enter, etc)

I think the Symfony docs mention this a bit, too, but the guards shouldn't do any actions at all, they should just say "yes/no" transition. Especially with Symfony 5, there are a bunch more events for each transition (leave, enter, entered, completed, announce).

I'm guessing that maybe your issues is that a value that wouldn't be defined in one of the transitions is being checked and that's causing the issue? You can grab the transition with `$event->getTransition()` to get `Transition` object.

Hope that helps! Let me know if you're seeing anything else.

**Comment by erikacamilleri** [comment]
> I'm curious, in this instance though, if having the same place in the `from` and `to` of the `prepare` transition is affecting that? Is it the same issue without `being_prepared` in the `from`?

Hello, thanks for the detailed replies I am deeply taking them into consideration so that I can work around this. I just would like to answer your last question - no if I remove the `being_prepared` in the from  of the `pick` transition then this behaviour will not happen.

I apologise for the delayed response. I will definitely shout out if I find anything else. This package is a core aspect of a project I am working on at the moment. Truly appreciate your contribution.
