### ISSUE TITLE
Argument 1 passed to Symfony\Component\Workflow\Marking::__construct() must be of the type array, string given,

### ISSUE THREAD

**Issue by p8520888** [zerodahero/laravel-workflow#31]
I'm try to Example 1. Exactly two places transition to one

to_review is worked.
![image](https://user-images.githubusercontent.com/37201041/99501141-51e9de00-29b6-11eb-956d-0351aad1384c.png)

when I want to try  publish.
I get a issue like this.
![image](https://user-images.githubusercontent.com/37201041/99499807-6af18f80-29b4-11eb-8199-3f65e8be7045.png)

and I try to fix it like this.
![image](https://user-images.githubusercontent.com/37201041/99500169-eb17f500-29b4-11eb-9eea-5356dc01b26f.png)
And It's worked.
But I don't know what happen.
I worried about it will be crashed.
Would you fix that?
thank you very much

**Comment by zerodahero** [comment]
Behind the scenes, Symfony is always treating the workflow marking as an array, with the only difference being a single-state workflow vs a multi-state workflow. Since yours is a multi-state workflow, make sure that you're casting your marking state to `array` or `json`.

Let me know if that works. This is a pretty common issue, so please let me know if there's a better way I can include this in the documentation. Thanks!
