### ISSUE TITLE
WorkflowRegistry

### ISSUE THREAD

**Issue by MathiasWeisheit** [zerodahero/laravel-workflow#41]
Hi, I started:
composer require zerodahero/laravel-workflow 

I get this error:
Argument 1 passed to ZeroDaHero\LaravelWorkflow\WorkflowRegistry::__construct() must be of the type array, null given, called in /app/vendor/zerodahero/laravel-workflow/src/WorkflowServiceProvider.php on line 49

**Comment by zerodahero** [comment]
Hi! Can you provide a bit more info?

Is that error directly from Composer, or when you try and do something in your app?
What version of PHP are you running?
What version of Laravel/Lumen are you pulling this into?
Can you post the full stack trace that's dumped out from that?

The error is related to the the config being missing. You'll need to publish the config (see the readme).

There might be an issue here if it's composer throwing this--but otherwise it looks like just the config file is missing.

**Comment by MathiasWeisheit** [comment]
hi , i use the laravel ide-helper
and the command php artisan ide-helper:generate generates this problem.
See line 66 in composer.jjson
[composer.json.txt](https://github.com/zerodahero/laravel-workflow/files/6134761/composer.json.txt)

**Comment by MathiasWeisheit** [comment]
i removed ide-helper form composer.json post-update
installed your package
published config
added ide-helper to composer.json
now it works
but can you fix the problem, too ?

**Comment by zerodahero** [comment]
Ah, ok, that makes more sense. I think this came up in the original repo way back before I forked this. The consensus there was that it wasn't worth fixing since it's not a "standard" feature of Laravel that causes that issue (the `register()` isn't typically run on the post-install hook).

The solution is to add a default blank config to the package service provider. While that fixes the problem you had, it's a bit weird from this package's perspective since it would allow for the possibility that this be installed/loaded but do "nothing." I'll see what I can do about a non-fatal error (or at least a better message), but from a typical package layout, I lean toward calling a missing config here "exceptional behavior".

**Comment by MathiasWeisheit** [comment]
If you want, you can close this issue.

**Comment by zerodahero** [comment]
I went ahead and threw a default on there for now (I'll circle back around to adding a better message in the future), and will likely be pushing that as v3.3.0 with some other changes.
