### ISSUE TITLE
Errors attempting to serialise a Closure if the event name cannot be mapped

### ISSUE THREAD

**Issue by simonworkhouse** [zerodahero/laravel-workflow#44]
If `DispatcherAdapter::translateEvent(...)` is unable to determine the event to map to, it just simply returns the Symfony event instead of an event which extends `ZeroDaHero\LaravelWorkflow\Events\BaseEvent`.

This causes the application to fail with the error `Serialization of 'Closure' is not allowed.` if a registered event listener implements the `Illuminate\Contracts\Queue\ShouldQueue` interface as the Symfony event contains Clousures and Laravel's queuing mechanism will always attempt to serialise the job.

One way to trigger this issue is to use a dot `.` character in the configured workflow name, such as `straight.test`.

There are a few potential solutions for this, but possibly parsing out the workflow name from the event name might be the best option (assuming that's feasible). Alternatively, disabling support for workflows with dot characters in their name is another viable option, although would be a breaking change.

Regardless of which solution is implemented, calls to `DispatcherAdapter::translateEvent(...)` should also ensure that they don't return Symfony events.

**Comment by simonworkhouse** [comment]
I have implemented a fix for this issue, but an alternative solution for the commit https://github.com/zerodahero/laravel-workflow/pull/45/commits/18daf0519f84cb71974229f9a01fe4bb52d7c6ea could be something to discuss. I had to wrap part of it in a try/catch due to issues in the Symony workflows package.

**Comment by zerodahero** [comment]
I'm not sure I'm fully understanding the issue here? We should be mapping all of the Symfony workflow events anyway, so the fallback to the Symfony event shouldn't be used? Are there events that don't map?

**Comment by zerodahero** [comment]
After looking a bit closer, it seems like the issues is centered around the `.` in the workflow name. A cursory glance at the Symfony component makes it seem like it's acceptable to do so (though I don't believe it matches their conventions since "_" is the primary separation character they use).

Considering that, we probably should still dispatch the right events, here 😉 . I pushed up a change to develop to handle the event translation through regex on the known events instead of relying on the explosion (which TBH felt awful anyway).

Let me know if that solves this issue, and/or if we still need to consider the changes in the PR as well. (I'll wait to close this until I hear back from you.)

**Comment by simonworkhouse** [comment]
@zerodahero Excellent, your fix works well for my use case, although the only potential issue I can think of is if someone names their workflow the same as one of the map keys, such as `transition` or `completed`. Maybe the regex could be expanded to account for this too?

As for the PR, I have merged in your updates so that you can consider a fallback event that extends `ZeroDaHero\LaravelWorkflow\Events\BaseEvent` instead of just returning a Symfony event that cannot be serialised.
