### ISSUE TITLE
Duplicate events dispatched.

### ISSUE THREAD

**Issue by hugeps** [zerodahero/laravel-workflow#50]
Events are dispatched twice - first w/o name then with name.  Is this intentional? 
Only need my event listener to fire once, but get it multiple times.

https://github.com/zerodahero/laravel-workflow/blob/b94e97340030f2522a1243367eff6d96db3dab40/src/Events/DispatcherAdapter.php#L41

**Comment by zerodahero** [comment]
Yes, there are multiple events dispatched for the same event. Since we're translating "Symfony" events to the "Laravel" event system, there's different scopes to the events (e.g. `workflow.some_workflow.transition.transition_name` as well as `workflow.transition`), but we shouldn't be seeing multiple of the exact same type of event being dispatched.

**Comment by hugeps** [comment]
I will try to cook a test case to reproduce this.
I'm registering it as follows, should I maybe change this somehow?

` $events->listen(
            'ZeroDaHero\LaravelWorkflow\Events\EnteredEvent',
            'App\Listeners\DocumentWorkflowSubscriber@onEntered'
        );`

**Comment by zerodahero** [comment]
That looks correct. One thing specifically for the "entered" event is that it is fired for objects without a known state that "enter" the workflow as well.

Let me know if you come up with a good test case for this. I think all of the core tests check that every event is fired, but I don't think they rely on exact counts (since we're checking every event that fires), so based on that, I wouldn't expect to see events (of the event class) fired twice.

**Comment by pengan95** [comment]
I think this part of `Symfony` code is triggered multiple times for compatibility with dot syntax style and class name style. And dot syntax style is more powerful. 

[\Symfony\Component\Workflow\Workflow::transition](https://github.com/symfony/workflow/blob/aac97c13b8f9642890a323b4b6879ad5186f3a3f/Workflow.php#L385)
```php
$this->dispatcher->dispatch($event, WorkflowEvents::TRANSITION);
$this->dispatcher->dispatch($event, sprintf('workflow.%s.transition', $this->name));
$this->dispatcher->dispatch($event, sprintf('workflow.%s.transition.%s', $this->name, $transition->getName()));
```

I don't understand the reason why the event is triggered twice in [DispatcherAdapter.php](https://github.com/zerodahero/laravel-workflow/blob/b94e97340030f2522a1243367eff6d96db3dab40/src/Events/DispatcherAdapter.php#L41).

> Yes, there are multiple events dispatched for the same event. Since we're translating "Symfony" events to the "Laravel" event system, there's different scopes to the events (e.g. `workflow.some_workflow.transition.transition_name` as well as `workflow.transition`), but we shouldn't be seeing multiple of the exact same type of event being dispatched.

**Comment by zerodahero** [comment]
@pengan95 yes, that's correct, we're trying to match the same granularity of events as the underlying Symfony component.

The intent behind dispatching twice in the adapter is fire both the specialized Laravel event by class name, _and_ by the Symfony dot syntax. I'm guessing that may be the problem though? If you're listening to just the class name, I think you might expect 3-4 events for every action (depending on the event)?

Does that line up with what you're seeing? If so, I can see what we can do about that--we would only want to be dispatching the event class once since the object itself contains all the context.

**Comment by hugeps** [comment]
IMO, lads you should be checking if there are any subscribers before firing. This is definitely going to produce multiple calls EVEN if you use dot syntax. Not happy.

**Comment by zerodahero** [comment]
@hugeps @pengan95 I just pushed up a small change (to develop) to the adapter to only dispatch the class by classname (Laravel style) once per batch of dot-style events (it dispatches on the generic event such as "workflow.leave" in order to always dispatch once).

Please let me know if that fixes the issue for you and I'll create a new release with it if so (it's currently on the `develop` branch, so you'll need to pull in the `dev-develop` version).

**Comment by hugeps** [comment]
@zerodahero As it turns out, this actually worked with the original version of the code, just should have stopped using the class name as you recommended in the beginning. 

```
    public function subscribe($events)
    {
        $events->listen(
//            'ZeroDaHero\LaravelWorkflow\Events\GuardEvent',   --- REMOVE THE OLD WAY
            'workflow.guard',                                                            --- DO IT SYMFONY WAY
            'App\Listeners\DocumentWorkflowSubscriber@onGuard'
        );
        $events->listen(
//            'ZeroDaHero\LaravelWorkflow\Events\EnteredEvent',
            'workflow.entered',
            'App\Listeners\DocumentWorkflowSubscriber@onEntered'
        );
    }

```

**Comment by babak271** [comment]
> @hugeps @pengan95 I just pushed up a small change (to develop) to the adapter to only dispatch the class by classname (Laravel style) once per batch of dot-style events (it dispatches on the generic event such as "workflow.leave" in order to always dispatch once).
> 
> Please let me know if that fixes the issue for you and I'll create a new release with it if so (it's currently on the `develop` branch, so you'll need to pull in the `dev-develop` version).

I also have this problem. After debugging, I found that I enter this event exactly 3 times.

**Comment by zerodahero** [comment]
Hi @babak271 , the change to fix this was released in v3.3.3. If this is still a problem, can you open up a new issue with more details, examples, and logs?

**Comment by babak271** [comment]
> Hi @babak271 , the change to fix this was released in v3.3.3. If this is still a problem, can you open up a new issue with more details, examples, and logs?

Thank you for your consideration. I've just wanted to point out that it dispatches exactly 3 events.

**Comment by zerodahero** [comment]
@babak271 yes, there are multiple events dispatched for workflow event that takes place. Depending on the granularity your listeners need you can adjust which ones to listen to or ignore.

**Comment by babak271** [comment]
@zerodahero I mean 3 times for a single event, not 3 different events. I'm using 3.3.3 version and facing this problem, but [this](https://github.com/zerodahero/laravel-workflow/issues/50#issuecomment-905459505) bypasses this issue.

**Comment by zerodahero** [comment]
@babak271 , can you open up a new issue for this with some more details? Specifically, I'm curious what class event is being fired 3 times, what does your workflow config look like, and whether the contents of the events are different or not. Thanks!
