### ISSUE TITLE
[feature request] Trait method for saving current state Marking

### ISSUE THREAD

**Issue by klimenttoshkov** [zerodahero/laravel-workflow#67]
Hi Zack,

Sometimes a workflow contains data that is updated in separate methods or processes. Saving the current state using `$model->save()` method may lead to unexpected results, for example race conditions with counters.

For this reason I am mostly using `$model->update(['marking' => $model->marking])` but this seems to me a bit hacky. What about having a dedicated method in `WorkflowTrait` for saving the state using the underlying MarkingStore?

**Comment by zerodahero** [comment]
Hi, I've seen this handled a number of different ways, and I've mostly opted out of taking a stance on it through this package (the main exception being the use of mutators/accessors defined in the `EloquentMarkingStore`). I think using `$model->update()` if you're running into race conditions is probably your best choice, but since it's very specific to the projects, I'm not convinced something like that should belong on the workflow trait (since that would "break" the typically Laravel conventions for models).

Here's a few of the ways I've seen this handled:
- The marking is handled exactly like a normal Eloquent attribute
- The marking is mostly a normal attribute, but uses a mutator/accessor to set/get from the table in a more specific way
- Use an event (typically `completed`) to run `save()` on the model to make sure that any `$model->workflow_apply(...)` calls update the marking in the DB immediately
- Use the `$model->update(...)` method as you described
- Use non-model objects with one of the Symfony marking stores (I've even seen this interact with the DB or Redis in limited form, but I'm not sure I'd recommend that approach in Laravel)

So we'd need to keep all of these approaches in mind as well for any trait changes (since they could cause unexpected results depending on which method).

I think specifically for your case the `$model->update(...)` on just the marking works well, and I think it would definitely be a great trait to add in to your project, but I'm not sure it's a good fit directly into this package as it would be somewhat unexpected behavior on an Eloquent model.

**Comment by klimenttoshkov** [comment]
Hi and thanks for taking the time to write detailed answer. I completely agree with all you've said. My idea is that because we have own implementation of `EloquentMarkingStore` that is fully aware of the format of the field and the name of the attribute, that it would be easy and compliant to extend it with `persistState()` method there, which will then be available through the Trait as well. Actually this method will not be in the model itself, avoiding the fat model paradigm. 

Right now yes, I do `$model->update()` but it requires to implicitly specify the marking name. This will be avoided when extending our own custom marking store. What do you think about that?

**Comment by zerodahero** [comment]
I think that's a great idea, but I think it's too specific to your project to be a part of the package directly. Persisting state in regards to the Eloquent models is pretty unique per project, and the general paradigm of Laravel/Eloquent is that a model is "working memory" and as such persisting is a matter entirely up to the project.

Thinking back to the projects I've used this in, immediately persisting the marking state would result in several extra round trips to the DB which would be very undesirable.
