### ISSUE TITLE
Upgrade to Laravel 10: got error getSubject()

### ISSUE THREAD

**Issue by seth-setiadha** [zerodahero/laravel-workflow#86]
Hi all,

I'm upgrading the app from Laravel 8 to 10 and I stumble upon this error "Call to a member function getSubject() on null" onthe following code 
public function onGuard(GuardEvent $event)  
{

        $originalEvent = $event->getOriginalEvent();
        /** @var App\Model\Result $post */
        $result = $originalEvent->getSubject();
        $title = $result->title;
        if (empty($title)) {
            // Posts with no title should not be allowed
            $originalEvent->setBlocked(true);
        }
    }

Not sure I know what's wrong and how to fix it. Please let me know if any of you face the same issue and know how to solve this.

Thank you

**Comment by zerodahero** [comment]
Since [v4.0.0](https://github.com/zerodahero/laravel-workflow/releases/tag/v4.0.0), the events from this package inherit directly from the Symfony events to address a few previous incompatibility issues with the proxied approach.

You should no longer need to call `->getOriginalEvent()`, just calling `->getSubject()` should work.
